# Generated by Django 5.1.5 on 2025-01-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(max_length=50)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('target_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_password_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fitness_goals',
            field=models.ManyToManyField(to='fitness_tracking_app.fitnessgoal'),
        ),
    ]
