# Generated by Django 5.1.5 on 2025-01-28 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracking_app', '0009_nutrition'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], help_text='Type of meal (e.g., Breakfast, Lunch, Dinner, Snack)', max_length=20)),
                ('total_calories', models.FloatField(help_text='Total calories of the meal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nutrition', models.ForeignKey(help_text='Reference to the Nutrition log', on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='fitness_tracking_app.nutrition')),
            ],
            options={
                'ordering': ['nutrition', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='NutritionMealFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Quantity of the food item in grams')),
                ('food_item', models.ForeignKey(help_text='Reference to the Food Item', on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_meal_food_items', to='fitness_tracking_app.fooditem')),
                ('nutrition_meal', models.ForeignKey(help_text='Reference to the Nutrition Meal', on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_meal_food_items', to='fitness_tracking_app.nutritionmeal')),
            ],
        ),
        migrations.AddField(
            model_name='nutritionmeal',
            name='food_items',
            field=models.ManyToManyField(help_text='Food items included in this meal', related_name='nutrition_meals', through='fitness_tracking_app.NutritionMealFoodItem', to='fitness_tracking_app.fooditem'),
        ),
        migrations.AlterUniqueTogether(
            name='nutritionmeal',
            unique_together={('nutrition', 'meal_type')},
        ),
    ]
