export const Messages = {
  SERVER_ERROR: 'Server error',
  // User-related messages
  USER_REGISTER_SUCCESS: 'User registered successfully',
  USER_REGISTER_ERROR: 'Error registering user',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  LOGIN_SUCCESS: 'Login successful',
  LOGIN_ERROR: 'Error logging in',
  INVALID_EMAIL_PASSWORD: 'Invalid email or password',
  RESET_LINK_SENT: 'Password reset link sent successfully',
  USER_NOT_FOUND: 'User not found',
  USER_ID_REQUIRED: 'User ID is required',
  PASSWORD_RESET_SUCCESS: 'Password reset successfully',
  PASSWORD_RESET_ERROR: 'Error resetting password',
  PROFILE_UPDATED_SUCCESS: 'Profile updated successfully',
  PROFILE_UPDATE_ERROR: 'Error updating profile',
  TOKEN_INVALID: 'Invalid or expired refresh token',
  REFRESH_TOKEN_MISSING: 'Refresh token is missing',
  REFRESH_TOKEN_INVALID: 'Invalid refresh token',
  ACCESS_TOKEN_REFRESHED: 'Access token refreshed successfully',
  PASSWORD_RESET_TOKEN_INVALID:
    'Password reset token is invalid or has expired',
  EMAIL_NOT_EXIST: 'User with this email does not exist',

  // Workout-related messages
  WORKOUTS_RETRIEVED_SUCCESS: 'Workouts retrieved successfully',
  WORKOUT_NOT_FOUND: 'Workout not found',
  WORKOUT_RETRIEVED_SUCCESS: 'Workout retrieved successfully',
  WORKOUT_CREATED_SUCCESS: 'Workout created successfully',
  WORKOUT_CREATE_ERROR: 'Error creating workout',
  WORKOUT_UPDATED_SUCCESS: 'Workout updated successfully',
  WORKOUT_RETRIVE_ERROR: 'Error retrieving workout',
  WORKOUT_UPDATE_ERROR: 'Error updating workout',
  WORKOUT_DELETED_SUCCESS: 'Workout deleted successfully',
  WORKOUT_DELETE_ERROR: 'Error deleting workout',

  // Workout exercise-related messages
  WORKOUT_EXERCISES_FETCHED_SUCCESS: 'Workout exercises fetched successfully',
  WORKOUT_EXERCISES_FETCHED_ERROR: 'Error fetching workout exercises',
  WORKOUT_EXERCISE_NOT_FOUND: 'Workout exercise not found',
  WORKOUT_EXERCISE_ADDED_SUCCESS: 'Exercise added to workout successfully',
  WORKOUT_EXERCISE_ADD_ERROR: 'Error adding exercise to workout',
  WORKOUT_EXERCISE_UPDATED_SUCCESS: 'Workout exercise updated successfully',
  WORKOUT_EXERCISE_UPDATE_ERROR: 'Error updating workout exercise',
  WORKOUT_EXERCISE_REMOVED_SUCCESS:
    'Exercise removed from workout successfully',
  WORKOUT_EXERCISE_REMOVE_ERROR: 'Error removing exercise from workout',

  // Exercise related messages
  EXERCISES_RETRIEVED: 'Exercises retrieved successfully',
  EXERCISE_RETRIEVED: 'Exercise retrieved successfully',
  EXERCISE_NOT_FOUND: 'Exercise not found',
  EXERCISE_CREATED: 'Exercise created successfully',
  EXERCISE_UPDATED: 'Exercise updated successfully',
  EXERCISE_DELETED: 'Exercise deleted successfully',
  ERROR_FETCHING_EXERCISES: 'Error fetching exercises',
  ERROR_RETRIEVING_EXERCISE: 'Error retrieving Exercise',
  ERROR_CREATING_EXERCISE: 'Error creating exercise',
  ERROR_UPDATING_EXERCISE: 'Error updating exercise',
  ERROR_DELETING_EXERCISE: 'Error deleting exercise',

  //Challenges related messages
  FETCH_SUCCESS: 'Challenges retrieved successfully',
  FETCH_ERROR: 'Error fetching challenges',
  NOT_FOUND: 'Challenge not found',
  CREATE_SUCCESS: 'Challenge created successfully',
  CREATE_ERROR: 'Error creating challenge',
  UPDATE_SUCCESS: 'Challenge updated successfully',
  UPDATE_ERROR: 'Error updating challenge',
  DELETE_SUCCESS: 'Challenge deleted successfully',
  DELETE_ERROR: 'Error deleting challenge',
  INVALID_DATA: 'Invalid data',
  RETRIEVE_SUCCESS: 'Challenge retrieved successfully',
  RETRIEVE_ERROR: 'Error fetching challenge',

  //FoodItem related messages
  FOOD_ITEMS_RETRIEVED_SUCCESS: 'Food items retrieved successfully',
  FOOD_ITEM_RETRIEVED_SUCCESS: 'Food item retrieved successfully',
  FOOD_ITEM_NOT_FOUND: 'Food item not found',
  FOOD_ITEM_CREATED_SUCCESS: 'Food item created successfully',
  FOOD_ITEM_UPDATED_SUCCESS: 'Food item updated successfully',
  FOOD_ITEM_DELETED_SUCCESS: 'Food item deleted successfully',
  VALIDATION_ERROR: 'Validation error',

  // MealPlan related messages
  MEAL_PLAN_RETRIEVED: 'Meal plans retrieved successfully',
  MEAL_PLAN_NOT_FOUND: 'Meal plan not found',
  MEAL_PLAN_CREATED: 'Meal plan created successfully',
  MEAL_PLAN_UPDATED: 'Meal plan updated successfully',
  MEAL_PLAN_DELETED: 'Meal plan deleted successfully',
  ERROR_FETCHING_MEAL_PLANS: 'Error fetching meal plans',
  ERROR_CREATING_MEAL_PLAN: 'Error creating meal plan',
  ERROR_UPDATING_MEAL_PLAN: 'Error updating meal plan',
  ERROR_DELETING_MEAL_PLAN: 'Error deleting meal plan',

  // Nutrition related messages
  NUTRITION_RETRIEVED: 'Nutrition entry retrieved successfully',
  NUTRITION_NOT_FOUND: 'Nutrition entry not found or unauthorized',
  NUTRITION_CREATED: 'Nutrition entry created successfully',
  NUTRITION_UPDATED: 'Nutrition entry updated successfully',
  NUTRITION_DELETED: 'Nutrition entry deleted successfully',
  ERROR_FETCHING_NUTRITIONS: 'Error fetching nutritions',
  ERROR_CREATING_NUTRITION: 'Error creating nutrition entry',
  ERROR_UPDATING_NUTRITION: 'Error updating nutrition entry',
  ERROR_DELETING_NUTRITION: 'Error deleting nutrition entry',

  //NutritionMeal related messages
  NUTRITION_MEAL_NOT_FOUND: 'Nutrition meal not found.',
  NUTRITION_MEAL_RETRIEVED: 'Nutrition meal retrieved successfully.',
  NUTRITION_MEALS_RETRIEVED: 'Nutrition meals retrieved successfully.',
  NUTRITION_MEAL_CREATED: 'Nutrition meal created successfully.',
  NUTRITION_MEAL_UPDATED: 'Nutrition meal updated successfully.',
  NUTRITION_MEAL_DELETED: 'Nutrition meal deleted successfully.',
  ERROR_FETCHING_NUTRITION_MEAL: 'Error fetching nutrition meal.',
  ERROR_FETCHING_NUTRITION_MEALS: 'Error fetching nutrition meals.',
  ERROR_CREATING_NUTRITION_MEAL: 'Error creating nutrition meal.',
  ERROR_UPDATING_NUTRITION_MEAL: 'Error updating nutrition meal.',
  ERROR_DELETING_NUTRITION_MEAL: 'Error deleting nutrition meal.',

  //Progress Tracking related messages
  PROGRESS_TRACKING_NOT_FOUND: 'Progress tracking not found.',
  PROGRESS_TRACKING_RETRIEVED: 'Progress tracking fetched successfully.',
  PROGRESS_TRACKINGS_RETRIEVED: 'Progress trackings retrieved successfully.',
  PROGRESS_TRACKING_ADDED: 'Progress tracking added successfully.',
  PROGRESS_TRACKING_UPDATED: 'Progress tracking updated successfully.',
  PROGRESS_TRACKING_DELETED: 'Progress tracking deleted successfully.',
  ERROR_FETCHING_PROGRESS_TRACKING: 'Error fetching progress tracking.',
  ERROR_FETCHING_PROGRESS_TRACKINGS: 'Error fetching progress trackings.',
  ERROR_ADDING_PROGRESS_TRACKING: 'Error adding progress tracking.',
  ERROR_UPDATING_PROGRESS_TRACKING: 'Error updating progress tracking.',
  ERROR_DELETING_PROGRESS_TRACKING: 'Error deleting progress tracking.',
  NO_PROGRESS_DATA_FOUND: 'No progress data found for this user.',
  INVALID_USER_ID_FORMAT: 'Invalid user ID format.',
  ERROR_FETCHING_PROGRESS_DATA: 'Error fetching progress data.',
  ERROR_FETCHING_USER_PROGRESS_TRACKINGS:
    'Error fetching user progress trackings.',

  //Workout Plan related messages
  WORKOUT_PLANS_RETRIEVED: 'Workout plans retrieved successfully',
  WORKOUT_PLAN_RETRIEVED: 'Workout plan retrieved successfully',
  WORKOUT_PLAN_NOT_FOUND: 'Workout plan not found',
  WORKOUT_PLAN_CREATED: 'Workout plan created successfully',
  WORKOUT_PLAN_UPDATED: 'Workout plan updated successfully',
  WORKOUT_PLAN_DELETED: 'Workout plan deleted successfully',
  ERROR_FETCHING_WORKOUT_PLANS: 'Error fetching workout plans',
  ERROR_FETCHING_WORKOUT_PLAN: 'Error fetching workout plan',
  ERROR_CREATING_WORKOUT_PLAN: 'Error creating workout plan',
  ERROR_UPDATING_WORKOUT_PLAN: 'Error updating workout plan',
  ERROR_DELETING_WORKOUT_PLAN: 'Error deleting workout plan',
};

export const StatusCodes = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};
