export const path = {
  HOME: '/',
  REGISTER: '/register',
  LOGIN: '/login',
  FORGET_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',
  MY_PROFILE: '/dashboard/my-profile',
  WORKOUT: '/dashboard/workouts',
  EXERCISE: '/dashboard/exercises',
  WORKOUT_EXERCISE: '/dashboard/workout-exercise',
  WORKOUT_PLAN: '/dashboard/workout-plan',
  CHALLENGE: '/dashboard/challenges',
  FOOD_ITEM: '/dashboard/food-items',
  MEAL_PLAN: '/dashboard/meal-plans',
  NUTRITION: '/dashboard/nutritions',
  NUTRITION_MEAL: '/dashboard/nutrition-meals',
  PROGRESS_TRACKINGS: '/dashboard/progress-tracking',
};
