export const path = {
  HOME: '/',
  REGISTER: '/register',
  LOGIN: '/login',
  FORGET_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',
  MY_PROFILE: '/my-profile',
  WORKOUT: '/workouts',
  EXERCISE: '/exercises',
  WORKOUT_EXERCISE: '/workout-exercise',
  WORKOUT_PLAN: '/workout-plan',
  CHALLENGE: '/challenges',
  FOOD_ITEM: '/food-items',
  MEAL_PLAN: '/meal-plans',
  NUTRITION: '/nutritions',
  NUTRITION_MEAL: '/nutrition-meals',
  PROGRESS_TRACKINGS: '/progress-tracking',
};
