name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify a specific version or 'latest'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            backend/node_modules
            frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies in the root directory
      - name: Install root dependencies
        run: npm install

      # Install dependencies and run tests in the backend
      - name: Install backend dependencies
        working-directory: backend
        run: |
          npm install
          npm run test -- --detectOpenHandles

      # Install dependencies, run tests, and build the frontend
      - name: Install frontend dependencies and build
        working-directory: frontend
        run: |
          npm install
          npm run test
          npm run build
